=== Longhorn CNCF Sandbox Project Proposal

*Name of Project:* Longhorn

*Project Description:*

Longhorn is a open source distributed block storage software for Kubernetes. Longhorn provides a lightweight and portable persistent storage support for any Kubernetes cluster, no matter where it is hosted.

Longhorn is designed to leverage the existing modern technologies as much as possible, like the high-speed, high capacity SSD and NVMe, and proven Linux storage features like sparse files and cgroups. In Longhorn, every volume is implemented by independent microservices, orchestrated by Kubernetes. With the help of Kubernetes and other technologies, the main code base of Longhorn is only about thirty thousand lines. It's written in Go and broken into well-defined clean modules, so it's easy to understand and work with.

Here are some highlight features of Longhorn:

* Enterprise-grade distributed storage software
* Incremental snapshot of the block storage
* Backup to the backup store (NFS or S3-compatible object storage) built on efficient change block detection mechanism
* Recurring snapshot and backup
* Cross-cluster disaster recovery volume with defined RTO and RPO
* Automated non-disruptive upgrade. You can upgrade the entire Longhorn software stack without disrupting running volumes.
* Intuitive GUI

**Architecture**

Longhorn consists of below major components:

**Engine**

Longhorn engines are directly responsible for implementing the Longhorn data plane. Data plane implements the reading and writing of block devices. When Longhorn receives a request for a new volume, it creates one engine and multiple replicas to implement the data plane of this volume. Longhorn will find some disks on different nodes that have enough space to store the volume and schedules replica to each of them. After replicas start, the engine will connect to the replicas, implement a block device and provide it to the node that the pod is running in. Then the block device would be formatted and mounted in the node, finally provided to the container as a volume.

As long as replicas are located in the different nodes, losing nodes wouldn't be a problem unless you lose all the nodes that replicas running on. Another benefit of this architect is, the data paths of the volumes are separated from each other. What may happen to one volume's data path won't affect any other volumes' data path, which makes the Longhorn volumes more resilient.

**Manager**

Longhorn manager is built on top of Kubernetes. It implements the control plane of storage operations. It uses CRD and Kubernetes API server to store Longhorn's state in the Kubernetes cluster. The manager relays on the Kubernetes controller pattern to manage the volume status. It also utilizates Kubernetes to implement pod orchestration, cron job, node failure detection, pod failure detection, log collection etc. Building on top of Kubernetes makes the manager implementation much simpler. The manager can focus on storage related operations thanks to the Kubernetes.

Besides engine and manager, Longhorn also have an intuitive GUI and a test suite which covers every major features of Longhorn. Integration test cases are required for new features and major bugs in Longhorn.

*Statement on alignment with CNCF mission:*

Longhorn project aligns with CNCF's mission of making cloud native computing ubiquitous. Today, persistent storage support varies from Kubernetes clusters to Kuberentes clusters. As a result, users cannot deploy stateful workloads that require persistent volumes and expect their stateful workloads to work on any Kubernetes cluster. By creating a portable and lightweight implementation of persistent storage volumes, Longhorn can make persistent storage support available on every Kubernetes cluster and thus can help drive the adoption of Kubernetes technology.

*Sponsors from TOC:* Alexis Richardson and Liz Rice

*Preferred maturity level:* Sandbox

*License:* Apache License v2.0

*Source control:* GitHub (https://github.com/rancher/longhorn)

Longhorn repositories include: (To be moved into a separate organization)

* https://github.com/rancher/longhorn
* https://github.com/rancher/longhorn-engine
* https://github.com/rancher/longhorn-engine-launcher
* https://github.com/rancher/longhorn-manager
* https://github.com/rancher/longhorn-ui
* https://github.com/rancher/longhorn-tests
* https://github.com/rancher/liblonghorn
* https://github.com/rancher/go-iscsi-helper
* https://github.com/rancher/sparse-tools
* https://github.com/rancher/backupstore

*External Dependencies:*

See https://github.com/rancher/longhorn/blob/master/external-dependency.md[external-dependency.md] for details.

The current default Longhorn frontend TGT has binary dependency on a modified version of upstream TGT project. The modified version is hosted at https://github.com/rancher/tgt , with GPLv2 license.

*Initial Committers*

 * Sheng Yang @yasker (Rancher Labs), since 10/2015
 * Darren Shepherd @ibuildthecloud (Rancher Labs), since 03/2016

**Current Maintainer**

 * Sheng Yang @yasker (Rancher Labs)

*Infrastructure requests (CI / CNCF Cluster):*

_Development needs:_

None at the moment.

_Production needs:_

None at the moment.

*Communication Channels:*

 * Slack: https://rancher-users.slack.com #longhorn-storage channel
 * Forum: https://forums.rancher.com/c/longhorn
 * Issue tracker: https://github.com/rancher/longhorn/issues

*Website:* https://github.com/rancher/longhorn/ (will move to https://longhorn.io soon)

*Release methodology and mechanics:*
The version of Longhorn is based on Senmatic Versioning 2.0.0. The version number follows the pattern of MAJOR.MINOR.PATCH. Currently we plan to do about 3 minor versions and 1 major per year. We will do patch releases according to the necessity.

*Social media accounts:*

 * WIP

*Existing sponsorship:* Rancher Labs

*Community size:*

GitHub https://github.com/rancher/longhorn/stargazers[600+ stars]

Slack channel #longhorn-storage https://rancher-users.slack.com[200+ users]
